apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: database
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
