apiVersion: v1
kind: Service
metadata:
  name: valkey-metrics
  namespace: database
  labels:
    app: valkey
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: valkey
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
